### ISSUE TITLE
 the visualization results

### ISSUE THREAD

**Issue by 116022017144** [clovaai/BESTIE#12]
Hello, author! Could you provide the code of  the visualization results? Thanks!

**Comment by ssyc123** [comment]
I also have the same question! Thanks!

**Comment by qjadud1994** [comment]
sorry for the late reply.

The code in `utils/decode.py` may help you, such as https://github.com/clovaai/BESTIE/blob/eb3f6fcb278598471d59b22f06612df691fd1e7c/utils/decode.py#L4-L24 and https://github.com/clovaai/BESTIE/blob/eb3f6fcb278598471d59b22f06612df691fd1e7c/utils/decode.py#L147-L163
