### ISSUE TITLE
About maskrcnn？

### ISSUE THREAD

**Issue by ZechengLi19** [clovaai/BESTIE#13]
Thanks for your perfect work. I want to reproduce your work. However, when I apply mask rcnn on it, I found the result is not match the result you provided. On VOC2012, map50 --> 48.3, On COCO2017, map50 --> 22.2. Can you tell me, how to reproduce the result on mask rcnn? By the way, I use  mask_rcnn_r50_fpn_1x on mmdetection as my mask rcnn config.

**Comment by lh-zhu** [comment]
Hi, I also meet the same problem now, have you solved this?

**Comment by ZechengLi19** [comment]
> Hi, I also meet the same problem now, have you solved this?

Sorry, I just give up.

**Comment by YangYi-hub** [comment]
Hi！I want to reproduce this work, too. Can you tell me how to get BESTIE's result for maskrcnn refinement, even though the map50 is 48.3.

**Comment by ZechengLi19** [comment]
> Hi！I want to reproduce this work, too. Can you tell me how to get BESTIE's result for maskrcnn refinement, even though the map50 is 48.3.

Two tips. 

(1) `alpha` of PAM, you need to visualize PAM to select a better `alpha` for coco dataset. 
(2) WSSS maps with CRF is better.

**Comment by YangYi-hub** [comment]
Thanks！But I have another problem. How can I obtain the instance segmentation results on the training set using my trained model?

**Comment by ZechengLi19** [comment]
> Thanks！But I have another problem. How can I obtain the instance segmentation results on the training set using my trained model?

This repository does not seem to provide this function. You need to implement this function yourself.

**Comment by YangYi-hub** [comment]
Thank you！Could you briefly explain how to use the trained bestie model to obtain predicted masks on the training set? And I have another question. Are the training and validation images used for training Mask R-CNN the same as those used for training and validating bestie?
