### ISSUE TITLE
web demo

### ISSUE THREAD

**Issue by AK391** [clovaai/BESTIE#3]
Hi, would you be interested in creating a web demo for BESTIE using Gradio on Hugging Face for CVPR 2022?

more info here: https://huggingface.co/cvpr

The Hub offers free hosting, and it would make your work more accessible and visible to the rest of the ML community. Models/datasets/spaces(web demos) can be added to a user account or organization similar to github.

here is a example Gradio Demo for dalle-mini: https://huggingface.co/spaces/dalle-mini/dalle-mini

and another example for a cvpr 2022 paper: https://huggingface.co/spaces/CVPR/ml-talking-face

and here is a guide for adding a web demo to a organization: https://huggingface.co/blog/gradio-spaces

Please let us know if you would be interested and if you have any questions, we can also help with the technical implementation.

**Comment by qjadud1994** [comment]
Thanks for the interesting suggestion.

However, the goal of our work is to reduce the annotation cost of segmentation (weak supervisor instance segmentation), not for demo.
So we conclude that we don't require the web demo for BESTIE.

If we need the web demo for any other work, we'll contact you!

Thanks.
