### ISSUE TITLE
The centerness in online pseudo label generation

### ISSUE THREAD

**Issue by mt-cly** [clovaai/BESTIE#5]
Hi, thanks for your work. I have a confusion about the online pseudo label generation in https://github.com/clovaai/BESTIE/blob/main/utils/utils.py#L332 . 
py, px = cy, cx , where (cy, cx) is the center of connected component, I wonder if it is right? In my view, it should be py, px=center of mask instead of py, px=center of connected component.
Thank you.

**Comment by qjadud1994** [comment]
It seems to be an error that occurred when we fixed the code.
Thank you for your insighful feeback.
After check it, we will fix it.

**Comment by mt-cly** [comment]
okay, it seems does not a matter, very very few cases would satisfied the condition of center_score < args.refine_thresh. Thank you.
