### ISSUE TITLE
COCO classes num?

### ISSUE THREAD

**Issue by ZechengLi19** [clovaai/BESTIE#9]
Thanks for your perfect work! Now I have a question. Could you tell me how many classes you use in COCO dataset? 90(following PMM)? or just 80? Thanks!

**Comment by RidiculeMaker** [comment]
> Thanks for your perfect work! Now I have a question. Could you tell me how many classes you use in COCO dataset? 90(following PMM)? or just 80? Thanks!
Hello, I'm also working on this recently, and the visualization of the offset map is very poor. Have you encountered the same problem?

**Comment by ZechengLi19** [comment]
> > Thanks for your perfect work! Now I have a question. Could you tell me how many classes you use in COCO dataset? 90(following PMM)? or just 80? Thanks!
> 
> Hello, I'm also working on this recently, and the visualization of the offset map is very poor. Have you encountered the same problem?
> 
> 

I just visualize the PAM. It  looks not bad. But sometimes spots, strips will appear. I just use the hyper-parameters offered by author.
And I don't evaluate the performance of BESTIE. Because I still struggle with PMM(WSSS model).

**Comment by 116022017144** [comment]
> > Thanks for your perfect work! Now I have a question. Could you tell me how many classes you use in COCO dataset? 90(following PMM)? or just 80? Thanks!
> > Hello, I'm also working on this recently, and the visualization of the offset map is very poor. Have you encountered the same problem?

hello,did you run the model by voc2012 dataset?I meet some problem,it's hard

**Comment by ZechengLi19** [comment]
> > > Thanks for your perfect work! Now I have a question. Could you tell me how many classes you use in COCO dataset? 90(following PMM)? or just 80? Thanks!
> > > Hello, I'm also working on this recently, and the visualization of the offset map is very poor. Have you encountered the same problem?
> 
> hello,did you run the model by voc2012 dataset?I meet some problem,it's hard

Can you tell me your problem? I think you can run voc model easily, just use provided weight.

**Comment by 116022017144** [comment]
> > > > Thanks for your perfect work! Now I have a question. Could you tell me how many classes you use in COCO dataset? 90(following PMM)? or just 80? Thanks!
> > > > Hello, I'm also working on this recently, and the visualization of the offset map is very poor. Have you encountered the same problem?
> > 
> > 
> > hello,did you run the model by voc2012 dataset?I meet some problem,it's hard
> 
> Can you tell me your problem? I think you can run voc model easily, just use provided weight.
Thanks,I solved it! I forgot loading the hrnet pretrained-weights,so the result was bad!

**Comment by ssyc123** [comment]
> 

Hi! I have a question how to visualize the offset map? If have codes? Thanks!

**Comment by ZechengLi19** [comment]
> 

I'm sorry, I just visualize the peak generated by PAM.

**Comment by ssyc123** [comment]
> > Thanks for your perfect work! Now I have a question. Could you tell me how many classes you use in COCO dataset? 90(following PMM)? or just 80? Thanks!
> > Hello, I'm also working on this recently, and the visualization of the offset map is very poor. Have you encountered the same problem?

Hi! I have a question about how to visualize the offset map. If have codes? Thanks!

**Comment by ssyc123** [comment]
> 

Thanks!
